### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by zyleee**
Hi LedjIn!

I have updated the payum dependency, to get the bundle work with the current sylius version.

Best regards,
Christian

### CODE REVIEW

**Comment by makasim** [comment]
It is not enough.... There are some BC breaks which have to addressed before you can use it with Sylius. Does it work for you?

**Comment by a2xchip** [comment]
@zyleee I have got it. Let me check! @makasim Is there incompatibilities with the current version? I use it in previous Sylius and not so informed about newest payum's api updates.

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/UPGRADE.md
https://github.com/Payum/PayumBundle/blob/master/UPGRADE.md

Current Sylius supports 0.14.x Payum

**Comment by zyleee** [comment]
Sorry @makasim @a2xchip my pull request is rubbish, ignore it. I'll have a look to the BC breaks and update the pull request then. Thanks for the links.

**Comment by a2xchip** [comment]
@zyleee OK

**Pull request closed without merging**
