### PR TITLE
Compatibility payum 0.13

### PR DESCRIPTION
**Pull request by zyleee**
Hi @a2xchip @makasim 

Next try. Made compatibility with Payum 0.13.x in this branch and if OK for you guys (and the branch is ok) I will then make compatibility for Payum 0.14.x and later Payum 0.15.x

I am not very familiar with Payum nor Sagepay yet, so any input welcome.

Cheers
Christian

### CODE REVIEW

**Comment by makasim** [comment]
Looks good, does it work for you?

**Comment by zyleee** [comment]
Yes, it works for me. Just updated composer.json for compatibility with Payum 0.14.x, just tested and works as well.

**Comment by a2xchip** [comment]
@zyleee Good job! Let me merge it then

**Comment by zyleee** [comment]
@a2xchip Great thx! Do you mind to add a new version tag? I will add then compatibility with payum 0.15.x in the next few days

**Comment by a2xchip** [comment]
@zyleee Just did it. :+1:

**Pull request merged**
